### ISSUE TITLE
ERR Static interface methods are only supported starting with Android N ?

### ISSUE THREAD

**Issue by Biangkerok32** [shreyashsaitwal/rush-cli#18]
Hi Sir Shreyash,

**ERR Static interface methods are only supported starting with Android N**

 ```
ERR Static interface methods are only supported starting with Android N (--min-api 24): androidx.browser.trusted.TrustedWebActivityDisplayMode androidx.browser.trusted.TrustedWebActivityDisplayMode.fromBundle(android.os.Bundle)

ERR Compilation failed
Failed
```

Im try build extension use androidx.browser library(browser-1.3.0.jar),and get error that :thinking: 
is bug or something ?

**Screenshots**

![error](https://user-images.githubusercontent.com/48493593/118010651-7200c580-b379-11eb-9ae1-d3460a05c334.PNG)

**Desktop**
 - OS: [Windows]
 - Version [8 Pro]
 - Java: [OpenJDK ]
 - OpenJDK version "1.8.0_265"
 - OpenJDK Runtime Environment (Zulu 8.48.0.53-CA-win64) (build 1.8.0_265-b11)
 - OpenJDK 64-Bit Server VM (Zulu 8.48.0.53-CA-win64) (build 25.265-b11, mixed mode)

**Comment by shreyashsaitwal** [comment]
What happens if you build with the optimization turned off? You can turn it off by passing the `--no-optimize` flag.

**Comment by Biangkerok32** [comment]
> --no-optimize

same errors sir,

**Comment by shreyashsaitwal** [comment]
Looks like one of the extension's dependencies is using a Java 8 language feature -- static interface methods. As of now, Rush doesn't support the use of the Java 8 language features (FYI, AI2 doesn't support it either). 

But yes, support for Java 8 language features is already on the roadmap and is planned for v1.2.0. You'll have to wait until then.

**Comment by shreyashsaitwal** [comment]
#22 has fixed this.
