### ISSUE TITLE
Error compiling project

### ISSUE THREAD

**Issue by laboratoriodosfundos** [shreyashsaitwal/rush-cli#25]
I can't compile any project, even though I create a new one and try to compile it afterwards.
My machine is clean and functional.
Is my java correct?
What could it be?
![image](https://user-images.githubusercontent.com/77299764/124683235-f61b8900-dea2-11eb-87c2-605df5034bc3.png)

**Comment by shreyashsaitwal** [comment]
You need Java Development Environment (JDK) installed on your system. You have Java Runtime Environment (JRE).

**Comment by laboratoriodosfundos** [comment]
It is indicating that I already have the JDK installed.
I do not understand.
![JDK](https://user-images.githubusercontent.com/77299764/124777362-87781300-df16-11eb-91ad-c46b5dbdd35d.png)

**Comment by laboratoriodosfundos** [comment]
I managed to solve it, the path was pointing to a strange java that was installed.
Thanks for listening.

**Comment by shreyashsaitwal** [comment]
Glad to know that! 👍🏻
