### ISSUE TITLE
Error if contain white space in user profile - windows

### ISSUE THREAD

**Issue by jerinjacob1999** [shreyashsaitwal/rush-cli#30]
**Describe the bug**
Installation and build failure on windows if user folder contain space

My Pc user folder name is ```Jerin Jacob```

**Screenshots**
![image](https://user-images.githubusercontent.com/23569103/141247354-864f4376-a1d0-4bb0-8607-d10885a40073.png)

I installed rush manually, but for building extension rush-cli still need Appdata folder.

It would be nice to have a option to manually choose installation path  

**Desktop**
 -  Windows 10

https://github.com/jerinjacob1999/rush-cli

**Comment by shreyashsaitwal** [comment]
> Installation and build failure on windows if user folder contain space

Thanks for reporting. Putting `classesDir.path` ([here](https://github.com/shreyashsaitwal/rush-cli/blob/43d314b554e9078a5db6d4a21894b75fec560c11/lib/commands/build_command/tools/compiler.dart#L135)) inside quotes while passing it to `javac` should solve this. I think there exist several more bugs like this where the file/dir paths are passed to executables not wrapped inside of quotes. Would you like to put in a PR for this?

> It would be nice to have a option to manually choose installation path

Agreed, having the ability to change the path to the data directory would be great. This will especially be helpful during development. I like the idea of storing the data-dir path in an environment variable as you implemented in your fork. Would you like to put in a PR for this as well?

**Comment by shreyashsaitwal** [comment]
Fixed by 01d7d642e6b144fe3c3a5509e2e5c9bd5ee94569.
