### ISSUE TITLE
Add support automation for VS Code

### ISSUE THREAD

**Issue by jewelshkjony** [shreyashsaitwal/rush-cli#43]
Add support automation for VS Code.
 
Please add automation support for Java and Kotlin languages in VS Code.

(Thanks for your Rush)

**Comment by shreyashsaitwal** [comment]
What do you mean by automation support?

**Comment by jewelshkjony** [comment]
When we code in Android studio, Android studio suggest us for best code. This suggestion is not working on VS code for Rush project. Please add this features in 2.0

**Comment by shreyashsaitwal** [comment]
So you basically mean intelli-sense features (autocompletion, etc.). I did put some efforts to make VSCode intelli-sense work for Rush projects previously, but never really got it working.

I will give it shot again, but can't promise anything. If you, or anyone else is interested in contributing this, you might want to look into [Eclipse configuration files](https://www.ibm.com/docs/en/spm/7.0.4?topic=eclipse-configuration-files). These are equivalent to the IntelliJ configuration files (found in `.idea`) folder and used by [Eclipse JDT lang server](https://github.com/eclipse/eclipse.jdt.ls) (this is what VSCode uses under-the-hood for providing Java lang support).

**Comment by shreyashsaitwal** [comment]
Will be available in v2.0.0.

PS: 1c328f5779b051caa96f4e67040e86eab9e1dc70

**Comment by ysfchn** [comment]
Just found out that you can create a `settings.json` file in the `.vscode` folder in the project directory (`.vscode/settings.json`), and point to the jar files where Rush has installed:

```json
{
    "java.project.referencedLibraries": [
        "deps/*.jar",
        "~/rush/dev-deps/**/*.jar",
        "~/rush/dev-deps/*.jar"
    ]
}
```

(Java Language Support extension by Red Hat must be installed.)

It apparently works:

![resim](https://user-images.githubusercontent.com/54748183/226103463-f40a6bb1-a95e-4420-9460-956cc3289e8b.png)

**Comment by shreyashsaitwal** [comment]
> ```json
> java.project.referencedLibraries
> ```

Wasn't aware this existed. Thanks a lot!

**Comment by jewelshkjony** [comment]
Yes it's really working.
But it's not working for kotlin, do you've any solution for kotlin too?

**Comment by ysfchn** [comment]
> But it's not working for kotlin, do you've any solution for kotlin too? 

I don't know, unfortunately. I accidentally found the above setting while playing with Java extension settings.
