### ISSUE TITLE
Please add Shadow blocks

### ISSUE THREAD

**Issue by jewelshkjony** [shreyashsaitwal/rush-cli#47]
Hello dear, you've already added helper blocks in Rush 2.0. Please add also shadow blocks 

[Shadow Blocks](https://community.appinventor.mit.edu/t/what-is-your-opinion-about-helper-blocks-in-app-inventor-gsoc-project-user-feedback/9057/18)

![shadow-blocks](https://user-images.githubusercontent.com/75406851/196016990-babcbc93-31b3-443a-b22b-79e4df75350c.gif)

**Comment by shreyashsaitwal** [comment]
Ask app inventor to add that, Rush can't do that.
