### ISSUE TITLE
Issue in README.md

### ISSUE THREAD

**Issue by inclinedadarsh** [shreyashsaitwal/rush-cli#49]
**Describe the bug**
In the last (TODO) section of README file, tasks should be listed as checkboxes but some code in the file doesn't preview them like checkboxes but rather like plain text.

**Expected behavior**
Those text should appear as checkboxes.

**Screenshots**
![image](https://user-images.githubusercontent.com/84132532/208809702-9424ee5e-c25f-4a83-af5a-46f86f8d53ec.png)

**Comment by shreyashsaitwal** [comment]
Thanks for reporting, fixed. 👍
