### ISSUE TITLE
Windows Archive corrupted

### ISSUE THREAD

**Issue by MatejaSrejic** [ShreyashSaitwal/rush-cli#7]
I'm not able to open the Windows archive. It downloads fine but seems corrupted:

![image](https://user-images.githubusercontent.com/75619038/113751730-87e0f200-970c-11eb-9f7d-9b4c18aaeaeb.png)

**Comment by ShreyashSaitwal** [comment]
Try unpacking it with 7zip or latest version of WinRAR. It is a tarball, and therefore, old versions of WinRAR can't extract it.

**Comment by MatejaSrejic** [comment]
Thanks, seemed to work.
