### ISSUE TITLE
Cannot create or build extension

### ISSUE THREAD

**Issue by jaxparrow07** [ShreyashSaitwal/rush-cli#9]
![image](https://user-images.githubusercontent.com/36300128/114266255-f080e500-9a12-11eb-8b7d-064c496d9c98.png)
Error When creating

![image](https://user-images.githubusercontent.com/36300128/114266236-d810ca80-9a12-11eb-8714-8f4a50a16f86.png)
Error when Building.<br>

I hope you'll fix those in the next release

**Comment by ShreyashSaitwal** [comment]
It looks like you've renamed the Rush executable (rush.exe). You aren't supposed to do so. Renaming it back to rush.exe would solve the Issue.

**Comment by jaxparrow07** [comment]
Actually, I am using linux the linux binary. I am using `alias` and even tried using the full path `/opt/rush/bin/rush`.

**Comment by ShreyashSaitwal** [comment]
Aliasing isn't currently supported. I'd rather suggest you to remove the alias.

**Comment by jaxparrow07** [comment]
Actually, the problem is not with the alias.

**Comment by ShreyashSaitwal** [comment]
It is because of aliasing. Internally, Rush invokes some shell commands, like `which rush`, and because `rush` is now aliased, the command doesn't work, and hence, the null pointer exception.
